### ISSUE TITLE
contributing: nx 18.1.1 to 18.3.5 `pnpm test.utils` error -> parseCLI is not a function

### ISSUE THREAD

**Issue by maiieul** [qwikifiers/qwik-ui#746]
When upgrading to nx 18.1.1 up to 18.3.5,

`pnpm test.utils` errors out:

>  NX   parseCLI is not a function

> TypeError: parseCLI is not a function
    at getOptions (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/@nx+vite@18.1.1_@swc-node+register@1.8.0_@swc+core@1.3.107_@types+node@18.19.33_nx@18.1.1_typ_sjtw54h3mfbbctleajcdv6utza/node_modules/@nx/vite/src/executors/test/lib/utils.js:49:33)
    at async vitestExecutor (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/@nx+vite@18.1.1_@swc-node+register@1.8.0_@swc+core@1.3.107_@types+node@18.19.33_nx@18.1.1_typ_sjtw54h3mfbbctleajcdv6utza/node_modules/@nx/vite/src/executors/test/vitest.impl.js:29:37)
    at async getLastValueFromAsyncIterableIterator (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/nx@18.1.1_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/utils/async-iterator.js:13:19)
    at async iteratorToProcessStatusCode (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/nx@18.1.1_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/command-line/run/run.js:42:29)
    at async handleErrors (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/nx@18.1.1_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/utils/params.js:9:16)
    at async process.<anonymous> (/Users/maieul/dev/qwik-ui/node_modules/.pnpm/nx@18.1.1_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/bin/run-executor.js:59:28)

**Comment by maiieul** [comment]
Closing as nx 19 works 💀
